# Generated by Django 5.2.4 on 2025-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_ingredient_meal_difficulty_meal_name_meal_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="cost_max",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="cost_min",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cost_max_kg",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cost_min_kg",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meal",
            name="quantity",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
