# Generated by Django 5.2.4 on 2025-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_ingredient_cost_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="cost_single",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
