# Generated by Django 5.2.4 on 2025-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_ingredient_cost_single"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="quantity",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost_max_kg",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost_min_kg",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost_single",
            field=models.IntegerField(blank=True),
        ),
    ]
