# Generated by Django 5.2.4 on 2025-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_rename_quantity_meal_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="portions",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
