# Generated by Django 5.2.4 on 2025-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_ingredient_cost_single"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="cost_max_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost_min_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost_single",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
