# Generated by Django 5.2.4 on 2025-07-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_ingredient_cost_max_kg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="cost_max_kg",
            new_name="cost_max",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="cost_min_kg",
            new_name="cost_min",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="cost_single",
        ),
    ]
