# Generated by Django 5.2.4 on 2025-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_rename_cost_max_kg_ingredient_cost_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="difficulty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
