# Generated by Django 5.2.4 on 2025-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_meal_portions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.TextField(
                blank=True,
                choices=[
                    ("pasta", "Pasta / Rice"),
                    ("meat", "Meat / Poultry"),
                    ("fish", "Fish / Seafood"),
                    ("eggs", "Eggs / Dairy"),
                    ("other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
