# Generated by Django 5.2.4 on 2025-07-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_useringredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="useringredient",
            name="local_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useringredient",
            name="local_portions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
