# Generated by Django 5.2.4 on 2025-07-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_useringredient_local_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermeal",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usermeal",
            name="meal",
        ),
        migrations.RemoveField(
            model_name="usermeal",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserIngredient",
        ),
        migrations.DeleteModel(
            name="UserMeal",
        ),
    ]
