# Generated by Django 5.2.4 on 2025-07-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_ingredient_user_meal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="portions",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pasta", "Pasta / Rice"),
                    ("meat", "Meat / Poultry"),
                    ("fish", "Fish / Seafood"),
                    ("eggs", "Eggs / Dairy"),
                    ("other", "Other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(related_name="meals", to="cart.ingredient"),
        ),
    ]
